### ISSUE TITLE
Error: Command failed: Invalid Parameter - -set

### ISSUE THREAD

**Issue by Meschacirung** [KnicKnic/WASM-ImageMagick#71]
Error: Command failed: Invalid Parameter - -set

    at ChildProcess.<anonymous> (E:\meschac\web work\im\node_modules\imagemagick\imagemagick.js:88:15)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12) timedOut: false, killed: false, code: 4, signal: null }

**Comment by KnicKnic** [comment]
CICD is able to build. https://dev.azure.com/oneeyedelf1/wasm-imagemagick/_build/results?buildId=444&view=results

see setup in https://github.com/KnicKnic/WASM-ImageMagick/blob/master/azure-pipelines.yml

**Comment by KnicKnic** [comment]
closing as issue exists for long time and no instructions to reproduce.
